#!/bin/bash -e

#
# This script is executed in the pre-remove phase
#
#   On Debian/Ubuntu
#       $1=remove    : indicates a removal
#       $1=purge     : indicates a removal --purge
#       $1=upgrade   : indicates an upgrade
#
# You must just use this script to stop the service and delete any directory or file
# that it not exists in package hierarchy standar.

STOP_REQUIRED=false
REMOVE_SERVICE=false

case "$1" in
    # Debian ####################################################
    remove|purge)
        STOP_REQUIRED=true
        REMOVE_SERVICE=true
    ;;
    upgrade)
        STOP_REQUIRED=true
    ;;
    deconfigure|failed-upgrade)
    ;;
    *)
        echo "pre remove script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


if command -v systemctl >/dev/null; then
    # Stops the service
    if [ "$STOP_REQUIRED" = "true" ]; then
        echo -e "Stopping python-debian-skeleton services..."
        if systemctl is-active python-debian-skeleton.service >/dev/null; then
            systemctl --no-reload stop python-debian-skeleton.service
        fi
        echo "... OK"
    fi

    if [ "$REMOVE_SERVICE" = "true" ]; then
        echo -e "Disabling python-debian-skeleton services..."
        if systemctl is-enabled python-debian-skeleton.service >/dev/null; then
            systemctl disable python-debian-skeleton.service > /dev/null 2>&1
        fi
        echo "... OK"
    fi
fi

# EXAMPLES: DELETE SYMLINKS AND DIRECTORIES
 #    if [ ${python-debian-skeleton_symlink} ]; then
 #           echo -e "Removing ${python-debian-skeleton_symlink}"
    # rm ${SYMLINK_HARDRELOAD} && echo -e "... OK"
 #    fi

 #    if [ ${python-debian-skeleton_tmp_dir} ]; then
    # echo -e "Removing ${python-debian-skeleton_tmp_dir}"
    # rm ${python-debian-skeleton_tmp_dir} && echo -e "... OK"
 #    fi

exit 0
